<!-- Notebook acadêmico — resolução de laboratório de Deep Learning. -->
<!-- Documentação: ../DOCUMENTACAO.md -->
> **Portfólio acadêmico:** saídas da última execução preservadas. Consulte o README para reprodução.


# Atividade Prática: Fundamentos Matemáticos para Deep Learning

**Duração Estimada:** 2h 30min

Este notebook foi desenvolvido para exercitar os conceitos matemáticos essenciais apresentados nos slides. Foque na manipulação de tensores e nas operações de cálculo/probabilidade usando `numpy`.

## 1. Bases de Python com NumPy
Antes de mergulharmos na matemática, precisamos dominar o `numpy`, a biblioteca padrão para álgebra linear em Python.

**Exercicio 1:** Crie um vetor numérico com os inteiros de zero a dez.

**Exercicio 2:** Crie uma matriz aleatória $3 \times 3$.

In [6]:
# Ex. 1
import numpy as np
vetor_inteiros = np.arange(11)
vetor_inteiros

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Ex 2
matriz_aleatoria = np.random.rand(3,3)
matriz_aleatoria

array([[0.67440239, 0.44800077, 0.77502029],
       [0.71498054, 0.72353974, 0.33914441],
       [0.01760122, 0.06386161, 0.50467168]])

## 2. Álgebra Linear: Operações com Tensores

**Exercício 3:** Crie duas matrizes $A$ e $B$ 2x2. Calcule o produto de Hadamard (elemento a elemento).

**Exercício 4:** Calcule o produto matricial (Dot Product) entre $A$ e $B$.

**Exercício 5:** Obtenha a transposta da matriz $A$.

In [37]:
# Ex. 3
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [38]:
B = np.array([[5, 6], [7, 8]])
B

array([[5, 6],
       [7, 8]])

In [39]:
prod_pontual = A * B
prod_pontual

array([[ 5, 12],
       [21, 32]])

In [40]:
# Ex. 4
produto_matricial = A @ B
produto_matricial

array([[19, 22],
       [43, 50]])

In [45]:
# Ex. 5
A_t = A.T
A_t

array([[1, 3],
       [2, 4]])

## 3. Cálculo Diferencial: Derivadas e Gradiente

**Exercício 6:** Defina uma função quadrática $f(x) = x^2 + 5x + 10$ e sua derivada analítica $f'(x)$. Realize 10 passos de uma otimização simples para encontrar um valor menor de $x$ partindo de $x=10$.

In [48]:
# Ex. 6
def f(x):
  return x**2 + 5*x + 10

def df(x):
  return 2*x + 5

x = 10.0
learn_rate = 0.1

for i in range(10):
  gradiente = df(x)
  passo = learn_rate * gradiente
  x = x - passo
  print(f'Passo {i+1}: X = {x:.2f} | Gradiente = {gradiente:.2f} | Passo = {passo:.2f}')

Passo 1: X = 7.50 | Gradiente = 25.00 | Passo = 2.50
Passo 2: X = 5.50 | Gradiente = 20.00 | Passo = 2.00
Passo 3: X = 3.90 | Gradiente = 16.00 | Passo = 1.60
Passo 4: X = 2.62 | Gradiente = 12.80 | Passo = 1.28
Passo 5: X = 1.60 | Gradiente = 10.24 | Passo = 1.02
Passo 6: X = 0.78 | Gradiente = 8.19 | Passo = 0.82
Passo 7: X = 0.12 | Gradiente = 6.55 | Passo = 0.66
Passo 8: X = -0.40 | Gradiente = 5.24 | Passo = 0.52
Passo 9: X = -0.82 | Gradiente = 4.19 | Passo = 0.42
Passo 10: X = -1.16 | Gradiente = 3.36 | Passo = 0.34


In [57]:
# Ex. 6 modificado
def f(x):
  return x**2 + 5*x + 10

def df(x):
  return 2*x + 5

x = 10.0
learn_rate = 0.1
tolerancia = 0.005
i = 0

while abs(df(x)>=tolerancia):
  i += 1
  gradiente = df(x)
  passo = learn_rate * gradiente
  x = x - passo
  print(f'Passo {i}: X = {x:.6f} | Gradiente = {gradiente:.2f} | Passo = {passo:.2f}')
  if (i>100):
    print('Limite de iterações atingido')
    break

Passo 1: X = 7.500000 | Gradiente = 25.00 | Passo = 2.50
Passo 2: X = 5.500000 | Gradiente = 20.00 | Passo = 2.00
Passo 3: X = 3.900000 | Gradiente = 16.00 | Passo = 1.60
Passo 4: X = 2.620000 | Gradiente = 12.80 | Passo = 1.28
Passo 5: X = 1.596000 | Gradiente = 10.24 | Passo = 1.02
Passo 6: X = 0.776800 | Gradiente = 8.19 | Passo = 0.82
Passo 7: X = 0.121440 | Gradiente = 6.55 | Passo = 0.66
Passo 8: X = -0.402848 | Gradiente = 5.24 | Passo = 0.52
Passo 9: X = -0.822278 | Gradiente = 4.19 | Passo = 0.42
Passo 10: X = -1.157823 | Gradiente = 3.36 | Passo = 0.34
Passo 11: X = -1.426258 | Gradiente = 2.68 | Passo = 0.27
Passo 12: X = -1.641007 | Gradiente = 2.15 | Passo = 0.21
Passo 13: X = -1.812805 | Gradiente = 1.72 | Passo = 0.17
Passo 14: X = -1.950244 | Gradiente = 1.37 | Passo = 0.14
Passo 15: X = -2.060195 | Gradiente = 1.10 | Passo = 0.11
Passo 16: X = -2.148156 | Gradiente = 0.88 | Passo = 0.09
Passo 17: X = -2.218525 | Gradiente = 0.70 | Passo = 0.07
Passo 18: X = -2.274820 |

## 4. Estatística e Probabilidade

**Exercício 7:** Implemente a função Softmax. Ela é fundamental para converter scores (logits) em uma distribuição de probabilidade onde a soma é 1. Use o vetor `[2.0, 1.0, 0.1]` como teste.

In [59]:
#Ex. 7
def softmax(x):
  e_x = np.exp(x-np.max(x))
  return e_x/e_x.sum(axis=0)

vetor = softmax([2,1,0.1])
print(vetor)
print(sum(vetor))

[0.65900114 0.24243297 0.09856589]
1.0


## Desafio: Manipulação de Dimensões

**Exercício 8:** Crie um tensor 3D de forma (2, 2, 2). Redimensione-o (reshape) para um vetor de 8 elementos e depois para uma matriz 4x2. Isso é comum ao 'achatar' imagens para redes neurais.

In [71]:
t3d = np.arange(8).reshape(2,2,2)
t3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
t3d.reshape(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
t3d.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])